#!/bin/sh

TMP_FILE="/tmp/wordladder.stat"
if [ -r "${TMP_FILE}" ]
then
    rm "${TMP_FILE}"
fi

files=`git diff --cached --name-status | awk '{print $2}'`
hasGo="NO"
for f in ${files}; do
    if [ ${f: -3} == ".go" ]
    then
        hasGo="YES"
    fi
done;

if [ "${hasGo}" == "NO" ]
then
    echo "Skipping tests: no Go files modified"
    exit 0
fi

# Run the unit tests, if any fail, then do not allow the commit to continue
echo "Running unit tests"
TEST_RESULTS="/tmp/wordladder_test_results.txt"
go test ./... > "${TEST_RESULTS}"
if [ "$?" -ne "0" ]
then
    echo "One or more unit tests failed, printing test output below: "
    cat "${TEST_RESULTS}"
    exit 1
fi

# Run wordladder on a large dictionary and profile the performance
echo "Running performance tests"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
PROFILE_PATH="./profiles/${BRANCH_NAME}/${TIMESTAMP}"
mkdir -p ${PROFILE_PATH}
CPU_PROFILE="${PROFILE_PATH}/cpu.prof"
MEM_PROFILE="${PROFILE_PATH}/mem.prof"
TRACE_PROFILE="${PROFILE_PATH}/trace.prof"
go build
./wordladder --dict ./dicts/million.dict --cpuprofile "${CPU_PROFILE}" --memprofile "${MEM_PROFILE}" --trace "${TRACE_PROFILE}" > "${TMP_FILE}"
git add ${CPU_PROFILE}
git add ${MEM_PROFILE}
git add ${TRACE_PROFILE}

go tool pprof -list="main.*" --alloc_space wordladder "${MEM_PROFILE}" > "${PROFILE_PATH}/mem.code"
go tool pprof -disasm="main.*" --alloc_space wordladder "${MEM_PROFILE}" > "${PROFILE_PATH}/mem.asm"
go tool pprof -list="main.*" wordladder "${CPU_PROFILE}" > "${PROFILE_PATH}/cpu.code"
go tool pprof -disasm="main.*" wordladder "${CPU_PROFILE}" > "${PROFILE_PATH}/cpu.asm"
git add "${PROFILE_PATH}/mem.*"
git add "${PROFILE_PATH}/cpu.*"

printf "\nProfile: %s" "${PROFILE_PATH}" >> "${TMP_FILE}"

printf "\n\n" >> /tmp/wordladder.stat
go tool pprof -text --alloc_space wordladder "${MEM_PROFILE}" >> "${TMP_FILE}"
